isaacg1/pyth

extra_parse.py, pyth.py
Arbitrary Augmented Assignnment
====================
A big feature missing from Pyth is augmented assignment except for ``~``. However, there is no real reason that this is not so. So, I went and implemented arbitrary augmented assignment. It works because in Pyth an equals sign should never directly follow a function (By function I mean anything listed in ``c_to_f``). Hence, we could fill in that gap of usage to implement augmented assignment in the traditional form (i.e. +=, -=). However, this can be made even more powerful by allowing arbitrary functions in ``c_to_f`` to be used in augmented assignment. This make ``*=`` possible, but also weird ones like ``s=`` or ``:=``.
Examples
------------
Traditional binary operator example:
==================================================
*=T3T …
=> Added Augmented Assignment

doc.txt, macros.py, web-docs.txt
This implements and closes #26. 
The elements in the list (or string) are equally distributed. `c4U5` will return `[[0, 1], [2], [3]]` and `c5"abc"` will return `['a', 'b', 'c', '', '']`.
=> Split lists into n pieces

data.py, macros.py
The "O" part of file I/O was missing and now that we have a bunch more free namespaces, I think it would be a good feature. Very simple, it either takes a seq or an element. Everything is converted to strings and sequences are joined by newlines. Then writes to the second arg which defaults to ``foo.txt``.
=> Added write functionality

doc.txt, macros.py, web-docs.txt
Though not used very often, reproducibility is still comes up a fair amount in randomness challenges and `$random.seed()$` kills your score. I have put it into all non-`seq` of `.x` though it most often will be used with ints. I don't think that such a small part  of the namespace is a big price to pay for seeding.
=> Added RNG seeding

data.py, doc.txt, macros.py, web-docs.txt
We didn't have a bunch of numbers that seem necessary, including e and pi.
I added `.n` function which returns from a list of numbers: [pi, e, sqrt(2), phi, infinity]
I also made the default for log the same as python, natural log.
P.S. Completely unrelated, the seeding seems not to be working in the online interpreter. Is it fully updated?
=> Added Mathematical Constants list

macros.py
There was a bug in `at_slice` since it didn't allow `None` for the end point. Easy fix. We don't have a variable preinitialized to `None` but just doing `.xT` will return the value from seeding which is None.
=> Fixed slice not allowing None

data.py
After the introduction of `reduce2`, we used that for the fold operator. However, this broke fold, because we forgot to update the name and the indicies for the variables in it. I fixed it.
P.S. This is really fragile, as we just saw. We need a better way, which i'll be working on, but here is the quick fix.
=> Fixed fold

macros.py, test.py
The new assign-method screwed up `A`, since `AGH,1 2` gets translated into `assign('(G,H)',(1,(2)))`. This code fixes the problem.
=> Fix for A (assign-pair)

macros.py
This only adds functionality and breaks nothing - without this using both `.z` and `.Q` in one script is impossible.
=> Make .z and .Q refer to same data.

doc.txt, macros.py, web-docs.txt
Just a nice feature to have for the I/O functions `'` and `.w`. Now if the filename starts with `http` its interpreted as a url and `urllib.request.urlopen` is used. Read does get request, write uses write data as post data, joining if dict into needed form. Both return parsed in same way as read as list of lines.
=> Made I/O functions support urls

doc.txt, macros.py, web-docs.txt
A huge roadblock to pyth participating in many challenges was image i/o. In many cases it was impossible, and even when `ppm` was allowed, headers and formatting kills your score when both parsing and generating. So I added native image support to `'` and `.w` with PIL.
`'` detects image file names and makes a nested array. It removes alpha when all 255 and condenses grayscale tuples into a single value.
`.w` detects arrays and does the reverse in regards to alpha and grayscale. I also changed the default filename behavior in `.w`. It now first creates a filename-prefix, defaulting to `"o"` which you can override by passing in like `"foo"`and then a suffix which defaults to `.png` and `.txt`. You cant override just suffix, but you both as expected like `"foo.jpg"`.
A possible improvement …
=> Added image I/O

docs/spec_comp.rst
The two examples were in the wrong place. Swapped.
=> Swapped the SliceFrom and SliceTo examples

macros.py
Since the `.w` for images was written before we got rid of tuples, and PIL expects tuples for the RGB, not lists, it wasn't working. Very small fix.
Also a simple fix to `.z` that prevented it from working offline by passing it through `iter()` with sentinel values.
=> Fixed .w for images

docs/simple-programs.rst
The way `?`, `A` and `.x` work has changed and this causes the examples to not function properly. I've corrected them, except the one that uses `.x` because I don't know how.
=> Fixed excercises to reflect latest version.

index.html, server.py
Adding scaffolding to existing code to make test suites is annoying, messes up byte counts, and does not work with multi-line inputs. So I added that to the online interpreter.
Above the normal input textbox, there is a gray link which says "Test Suite ->":
Then when you click on that, it changes the textbox to another one and adds numeric input for input size:
When you run it, it runs all of them, and then returns their outputs, separated by linebreaks. The debug parameter is only honored on the first test, the rest all have no debug:
The permalinks all also work pretty naturally. Both textboxes are preserved over permalinks, though obviously, it also preserves which one was the current one.
Internally, I have encapsulated the code running in a function, and made two separate handlers …
=> Added test suite feature to interpreter

rev-doc.txt
The docs for `.[` (pad) don't match the implementation.
The implementation is rather messy, but I read through it carefully, and this change should reflect the actual code.
=> Fix documentation of .[

macros.py
`.d` for time < 10 secs cannot be done since it will be interpreted as the other keys. This lets you sleep for small periods of time by dividing the time given by 10. I initially had the idea of simply doing miliseconds as input, but this seemed like a better idea.
=> Made .d sleep more useful

pyth.py
I found myself using Pyth for a lot of daily "desktop calculator" tasks, so I wrote a little REPL for it. This is called up when one has no cmd args, or uses the `-r` or `--repl` flags.
It just runs each line as a program, but sends the output of one into the other allowing things like: 
```
>>> 6
6
>>> y
12
>>> 
24
>>> +3
27
>>> U
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
```
(Note that an empty line repeats the previous command).
It also uses the [`cmd`](https://docs.python.org/3/library/cmd.html) module for up-arrow/down-arrow history functionality.
I also included `help` functionality that lookups the command you enter in the docs:
```
>>> help h
h  <num>                  A + 1.
>>> ? m
m  <l:d> <col/num>        Map A(_) over B. …
```
=> Added REPL mode

pyth.py
Fixes #203.
I'm not "happy" with the flag parsing duplication, but the rest of the code uses `sys.argv[1:-1]` to remove the file (last arg), so we can't use that here... But that means `./pyth.py -rd` won't work >.>
=> Add debug flag support to REPL mode

macros.py
Use a recursive algorithm based on repeatedly squaring the base for both `to_base_ten` and `from_base_ten`.  The `from_base_ten` speedup is not as huge as I hoped, because Python’s divmod is [pathetically slow](https://bugs.python.org/issue3451), but it at least it’s slow C code rather than slow Python code.
Here are some benchmarks:
```
Old to_base_ten:
lC*d    100000    2.6s
lC*d    200000   10s
lC*d    400000   42s
New to_base_ten:
lC*d    100000    0.046s
lC*d    200000    0.093s
lC*d    400000    0.19s
⋮
lC*d  12800000    7.5s
lC*d  25600000   16s
lC*d  51200000   39s
Old from_base_ten:
lC^256   50000    4.9s
lC^256  100000   19s
lC^256  200000   76s
New from_base_ten:
lC^256   50000    0.12s
lC^256  100000    0.37s
lC^256  200000    1.3s
lC^256  400000    4.8s
lC^256  800000   19s …
```
=> Huge asymptotic speedup for base conversion

pyth.py
It adds the `-D` or `--only-debug` flag to only show debug informations
without executing the given code. With this enabled, the -d flag may or may
not be present.
NOTE: Doesn't work with REPL, but I don't think that would be useful.
=> Added flag to disable code execution

pyth.py
If the program is not linked to a tty (thus running from a non-interactive shell), run the program given from stdin.
Supports multiline input.
Fixes #208
Example usage : 
```bash
$ echo 'V5"helllo, world' | pyth.py
hello, world
hello, world
hello, world
hello, world
hello, world
```
=> Added interactivity check from #208

macros.py
The old code gave an incorrect result for A < B ≤ 2·A and an error for B < 0.  This fixes `.c A B` to be defined for all integers A, B consistently with M.J. Kronenburg, “The Binomial Coefficient for Negative Arguments” (2011), https://arxiv.org/abs/1105.3689.
=> Fix binomial coefficient computation (.C A B) for A < B ≤ 2·A

macros.py
Currently, doing `*_2"abc` will return an empty string. With the patch, the result would be `cbacba` which is more useful.
=> Multiplying a string by a negative number returns the reversed string multiplied

data.py
The else statement `.?` right now requires you to manually deindent with `)`'s or `;`. However, there is no need to make them deindent that final level, as that is already unambiguous.
I made `.?` a replacement parse that adds a `)` before the else. This lets you do things like `IQ1.?2`. Even in the case where you want to deindent multiple layers with a `;` and then do an else, it only adds an extra blank line, and doesn't add any extra chars: `IQVQN;.?_1`.
This is  a change to `.?`, not `I`, so it'll work for all the other control structures else works with.
=> Made else statement auto deindent

data.py, macros.py
There's already some special casing for `*` in `F`, so I went all the way and replaced `.!` with `*F`. For example: you can `*FT`, or `*F12.345` which calls the existing factorial macro. Not only does this clear up a char for later use, but it also makes mapping factorial much easier like: `*MT` for a list of factorials `[0,10)`.
=> Moved factorial to *F
