isaacg1/pyth

- index.py
- pyth.py
- safe_pyth.py
- server.py
On my machine `/usr/bin/python3` doesn't exist, however `/usr/local/bin/python3` does.
> Change shebang to /usr/bin/env python3 and add it to server.py

- .gitignore
- index.html
- server.py
- web-docs.txt
As suggested by @Maltysen in #10
> Move server functionality into different functions

- index.html
- server.py
> Safely escape server output

- safe_pyth.py
> Use ast.literal_eval instead of custom restricted_eval

- doc.txt
- macros.py
New feature. 
I think cartesian product for *<list><list> is quite suitable. 
Also did some tests with it.
> *<list><list> computes cartesian product

- index.html
- server.py
A major component missing from the web interpreter was a permalink feature. I have added that in now and it captures the code, input, and whether or not the debug checkbox was checked. It uses get url parameters and uses Jquery's url parameter encoding function. I have also implemented a few other things including a key binding in the text-boxes such that ctrl-enter is a shortcut to run the code and made some slight formatting changes to accommodate the debug window and made the output scrollable when it gets too large. Last, I also made the default for the debug checkbox checked.
> Added Permalink Feature

- data.py
- doc.txt
- macros.py
- web-docs.txt
Pretty much title.Observation by @jakobkogler https://github.com/isaacg1/pyth/pull/32#issuecomment-86021867 .
> Remove .r, useless in current state.

- data.py
- doc.txt
- web-docs.txt
Fixes https://github.com/isaacg1/pyth/issues/34 .
> added .u 'unpack and close', made docs consistent and fixed transition i -> .w

- pyth.py
Implements https://github.com/isaacg1/pyth/issues/36.
> Implements multi-line mode.

- doc.txt
- pyth.py
- web-docs.txt
Fixes #39, spelling error and pep8 indentation.
> Autoinitializing input variable bug

- macros.py
> When using a list as key for a dict, convert list to tuple automatically.

- doc.txt
- macros.py
- test.py
- web-docs.txt
For https://github.com/isaacg1/pyth/issues/60.
> Implement indexed substitution.

- macros.py
> Added negative infinity and nan.

- macros.py
Temporary bandaid for https://github.com/isaacg1/pyth/issues/59.
> Cache output of .z and .Q.

- data.py
- macros.py
https://github.com/isaacg1/pyth/issues/65
> Implement Phash.

- index.html
> Fix incorrect length on load

- doc.txt
- macros.py
- web-docs.txt
Reverts isaacg1/pyth#120
PIL is not in maintenance, and has no official version for Python 3. I'd rather not use it.
> Revert "Added image I/O"

- doc.txt
- macros.py
- web-docs.txt
Reverts isaacg1/pyth#121
I didn't realise that this uses pillow, not PIL, which is fine.
> Revert "Revert "Added image I/O""

- index.html
4 things added to web interpreter:
1. Better escaping in permalinks to be able to use them in markdown.
2. Loading animation on code submission.
3. On debug, input shows up in output box - this did not change the server, it all happens in js.
4. Using HTML5 history api `history.pushState()` instead of `document.location` for permalinks so no need for full reload.
> Web Interpreter Revamp

- pyth.py
In particular, the first assertion confused me a bit when I first encountered it.
> Better error messages in some contexts

- rev-doc.txt
> Add .v and .V to docs

- docs/simple-programs.rst
> Fix compiled code in example

- docs/spec_control.rst
> Update to current implementation of .? and ?

- data.py
- macros.py
.+  <seq> Deltas. Returns the differences between consecutive elements of A.
> Added .+ [deltas]

- docs/getting-started.rst
I thought some of the words were unnecessary. I could be wrong.
> Removed some words.

- docs/details.rst
Removed words from details.rst. Also, made a couple small structural changes.
> Updated details.rst

- macros.py
Consider automatically running `pyflakes` (or `flake8`), which would have caught this.
> Fix .C (combinations_with_replacement)
